# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.6

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/local/bin/cmake

# The command to remove a file.
RM = /opt/local/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /opt/local/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/sudeep/Code/cv

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/sudeep/Code/cv

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/sudeep/Code/cv/CMakeFiles /Users/sudeep/Code/cv/CMakeFiles/progress.make
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/sudeep/Code/cv/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ../bin/face

# Build rule for target.
../bin/face: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ../bin/face
.PHONY : ../bin/face

# fast build rule for target.
../bin/face/fast:
	$(MAKE) -f src/CMakeFiles/../bin/face.dir/build.make src/CMakeFiles/../bin/face.dir/build
.PHONY : ../bin/face/fast

#=============================================================================
# Target rules for targets named ../bin/vkeybd

# Build rule for target.
../bin/vkeybd: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ../bin/vkeybd
.PHONY : ../bin/vkeybd

# fast build rule for target.
../bin/vkeybd/fast:
	$(MAKE) -f src/CMakeFiles/../bin/vkeybd.dir/build.make src/CMakeFiles/../bin/vkeybd.dir/build
.PHONY : ../bin/vkeybd/fast

#=============================================================================
# Target rules for targets named srcs

# Build rule for target.
srcs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 srcs
.PHONY : srcs

# fast build rule for target.
srcs/fast:
	$(MAKE) -f src/CMakeFiles/srcs.dir/build.make src/CMakeFiles/srcs.dir/build
.PHONY : srcs/fast

#=============================================================================
# Target rules for targets named blobs

# Build rule for target.
blobs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 blobs
.PHONY : blobs

# fast build rule for target.
blobs/fast:
	$(MAKE) -f third/blobs/CMakeFiles/blobs.dir/build.make third/blobs/CMakeFiles/blobs.dir/build
.PHONY : blobs/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ../bin/face"
	@echo "... ../bin/vkeybd"
	@echo "... srcs"
	@echo "... blobs"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

